import { createFileRoute } from "@tanstack/react-router";
import { AnimatePresence, motion } from "motion/react";
import {
  ArrowRight, Award, BookOpen, BriefcaseBusiness, Check, ChevronDown, Compass,
  FileSearch, GraduationCap, LayoutDashboard, Menu, Moon, Search, Sparkles,
  Sun, Target, TrendingUp, UploadCloud, Users, X, Zap,
} from "lucide-react";
import { useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "CareerBridge — Your career, no connections needed" },
    { name: "description", content: "Four AI-powered career agents helping students improve resumes, choose careers, find scholarships, and discover jobs." },
    { property: "og:title", content: "CareerBridge — AI career guidance for students" },
    { property: "og:description", content: "Equal-opportunity career guidance, from your first resume to your first job." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ] }),
  component: CareerBridge,
});

type Agent = "overview" | "resume" | "career" | "scholarship" | "jobs";
const agents = [
  { id: "resume" as const, title: "Resume Evaluator", short: "Resume", desc: "Turn your resume into an interview-ready story.", icon: FileSearch, color: "text-primary", bg: "bg-secondary" },
  { id: "career" as const, title: "Career & Exam Guide", short: "Guidance", desc: "Find paths that fit your strengths and interests.", icon: Compass, color: "text-accent-foreground", bg: "bg-accent/70" },
  { id: "scholarship" as const, title: "Scholarship Finder", short: "Scholarships", desc: "Discover funding and free learning resources.", icon: GraduationCap, color: "text-success", bg: "bg-success/10" },
  { id: "jobs" as const, title: "Job Matcher", short: "Jobs", desc: "Match your skills to roles where you can thrive.", icon: BriefcaseBusiness, color: "text-primary", bg: "bg-secondary" },
];

const MotionButton = motion.create(Button);
const rise = { initial: { opacity: 0, y: 24 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, margin: "-60px" }, transition: { duration: .55 } };

function CareerBridge() {
  const [dark, setDark] = useState(false);
  const [view, setView] = useState<"home" | "dashboard">("home");
  const [agent, setAgent] = useState<Agent>("overview");
  const [menu, setMenu] = useState(false);
  const rootRef = useRef<HTMLDivElement>(null);

  const goDashboard = (next: Agent = "overview") => { setAgent(next); setView("dashboard"); setMenu(false); window.scrollTo({ top: 0, behavior: "smooth" }); };
  return (
    <div ref={rootRef} className={dark ? "dark" : ""}>
      <div className="min-h-screen overflow-x-hidden bg-background text-foreground transition-colors duration-300">
        <Navbar dark={dark} setDark={setDark} view={view} setView={setView} goDashboard={goDashboard} menu={menu} setMenu={setMenu} />
        <AnimatePresence mode="wait">
          {view === "home" ? <Landing key="home" goDashboard={goDashboard} /> : <Dashboard key="dashboard" agent={agent} setAgent={setAgent} />}
        </AnimatePresence>
      </div>
    </div>
  );
}

function Navbar({ dark, setDark, view, setView, goDashboard, menu, setMenu }: { dark: boolean; setDark: (v:boolean)=>void; view:string; setView:(v:"home"|"dashboard")=>void; goDashboard:(a?:Agent)=>void; menu:boolean; setMenu:(v:boolean)=>void }) {
  const home = () => { setView("home"); setMenu(false); window.scrollTo({top:0, behavior:"smooth"}); };
  return <header className="sticky top-0 z-50 border-b border-border/70 bg-background/80 backdrop-blur-xl">
    <nav className="mx-auto grid h-18 max-w-7xl grid-cols-[minmax(0,1fr)_auto] items-center gap-3 px-5 sm:px-8">
      <button onClick={home} className="flex min-w-0 items-center gap-2.5 cursor-pointer" aria-label="CareerBridge home">
        <span className="grid size-9 shrink-0 place-items-center rounded-xl bg-gradient-brand text-primary-foreground shadow-glow"><Sparkles size={18}/></span>
        <span className="truncate font-display text-xl font-extrabold">Career<span className="text-primary">Bridge</span></span>
      </button>
      <div className="hidden items-center gap-7 md:flex">
        <button onClick={home} className="text-sm font-semibold text-muted-foreground transition-colors hover:text-foreground">Home</button>
        <a href={view === "home" ? "#features" : "/#features"} className="text-sm font-semibold text-muted-foreground transition-colors hover:text-foreground">Features</a>
        <button onClick={()=>goDashboard()} className="text-sm font-semibold text-muted-foreground transition-colors hover:text-foreground">Dashboard</button>
        <a href={view === "home" ? "#about" : "/#about"} className="text-sm font-semibold text-muted-foreground transition-colors hover:text-foreground">About</a>
      </div>
      <div className="flex items-center justify-end gap-2">
        <Button variant="ghost" size="icon" onClick={()=>setDark(!dark)} aria-label={dark ? "Switch to light theme" : "Switch to dark theme"} className="relative overflow-hidden rounded-full">
          <AnimatePresence mode="wait" initial={false}>{dark ? <motion.span key="sun" initial={{opacity:0,rotate:-90}} animate={{opacity:1,rotate:0}} exit={{opacity:0,rotate:90}}><Sun/></motion.span> : <motion.span key="moon" initial={{opacity:0,rotate:90}} animate={{opacity:1,rotate:0}} exit={{opacity:0,rotate:-90}}><Moon/></motion.span>}</AnimatePresence>
        </Button>
        <Button variant="hero" className="hidden sm:inline-flex" onClick={()=>goDashboard()}>Login / Signup</Button>
        <Button variant="ghost" size="icon" className="md:hidden" onClick={()=>setMenu(!menu)} aria-label="Open navigation">{menu?<X/>:<Menu/>}</Button>
      </div>
    </nav>
    <AnimatePresence>{menu && <motion.div initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}} className="overflow-hidden border-t border-border bg-surface-strong md:hidden"><div className="grid gap-2 p-4"><Button variant="ghost" onClick={home}>Home</Button><Button variant="ghost" onClick={()=>goDashboard()}>Dashboard</Button><Button variant="hero" onClick={()=>goDashboard()}>Login / Signup</Button></div></motion.div>}</AnimatePresence>
  </header>;
}

function Landing({ goDashboard }: { goDashboard:(a?:Agent)=>void }) {
  return <motion.main initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}} transition={{duration:.3}}>
    <section className="relative min-h-[730px] overflow-hidden border-b border-border/60 pt-24 ambient-grid">
      <div className="pointer-events-none absolute inset-0 bg-gradient-to-b from-background/20 via-background/80 to-background" />
      <motion.div animate={{y:[0,-12,0],rotate:[0,3,0]}} transition={{duration:6,repeat:Infinity,ease:"easeInOut"}} className="absolute left-[7%] top-36 hidden size-14 place-items-center rounded-2xl border border-primary/20 bg-surface text-primary shadow-soft lg:grid"><Target/></motion.div>
      <motion.div animate={{y:[0,14,0],rotate:[0,-4,0]}} transition={{duration:7,repeat:Infinity,ease:"easeInOut"}} className="absolute right-[8%] top-52 hidden size-14 place-items-center rounded-2xl border border-accent/30 bg-surface text-accent-foreground shadow-soft lg:grid"><Award/></motion.div>
      <div className="relative mx-auto max-w-5xl px-5 text-center sm:px-8">
        <motion.div initial={{opacity:0,scale:.9}} animate={{opacity:1,scale:1}} className="mx-auto mb-7 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-secondary px-4 py-2 text-sm font-semibold text-primary"><Zap size={15}/> Four AI agents. One confident future.</motion.div>
        <motion.h1 initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{delay:.1,duration:.6}} className="mx-auto max-w-4xl font-display text-5xl font-extrabold leading-[1.04] sm:text-7xl lg:text-8xl">Your career,<br/><span className="text-gradient-brand">no connections needed.</span></motion.h1>
        <motion.p initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.22}} className="mx-auto mt-7 max-w-2xl text-lg leading-8 text-muted-foreground sm:text-xl">Personal guidance, practical opportunities, and a fair start—for every student, from every background.</motion.p>
        <MotionButton initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.35}} variant="hero" size="lg" className="mt-9" onClick={()=>goDashboard()}>Get Started <ArrowRight/></MotionButton>
        <motion.div initial={{opacity:0,y:35}} animate={{opacity:1,y:0}} transition={{delay:.5,duration:.65}} className="mx-auto mt-16 grid max-w-4xl grid-cols-2 gap-3 rounded-2xl border border-border bg-surface p-3 shadow-soft backdrop-blur-xl sm:grid-cols-4">
          {[['72','ATS Score'],['89%','Career Fit'],['12','Scholarships'],['24','Job Matches']].map(([n,l])=><div key={l} className="rounded-xl bg-background/60 px-4 py-5"><div className="font-display text-2xl font-extrabold text-primary">{n}</div><div className="mt-1 text-xs font-semibold text-muted-foreground">{l}</div></div>)}
        </motion.div>
      </div>
    </section>
    <section id="features" className="mx-auto max-w-7xl px-5 py-24 sm:px-8">
      <motion.div {...rise} className="mb-12 max-w-2xl"><p className="mb-3 text-sm font-bold uppercase text-primary">Your support system</p><h2 className="text-4xl font-extrabold sm:text-5xl">Four experts in your corner.</h2><p className="mt-4 text-lg text-muted-foreground">Move from uncertainty to opportunity with guidance built around you.</p></motion.div>
      <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">{agents.map((a,i)=><motion.article key={a.id} {...rise} transition={{delay:i*.08,duration:.5}} whileHover={{y:-8}} className="group relative overflow-hidden rounded-2xl border border-border bg-card p-6 shadow-soft backdrop-blur-md transition-shadow hover:shadow-glow"><div className={`mb-8 grid size-12 place-items-center rounded-xl ${a.bg} ${a.color}`}><a.icon className="transition-transform group-hover:rotate-6 group-hover:scale-110"/></div><h3 className="text-xl font-bold">{a.title}</h3><p className="mt-3 min-h-12 text-sm leading-6 text-muted-foreground">{a.desc}</p><Button variant="ghost" className="mt-6 px-0 text-primary" onClick={()=>goDashboard(a.id)}>Try it <ArrowRight/></Button></motion.article>)}</div>
    </section>
    <section className="border-y border-border bg-secondary/45"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[1fr_1.2fr] lg:items-center"><motion.div {...rise}><p className="text-sm font-bold uppercase text-primary">Impact that compounds</p><h2 className="mt-3 text-4xl font-extrabold">Small steps. Real momentum.</h2><p className="mt-4 max-w-lg text-muted-foreground">Built to help students make informed decisions without needing insider access.</p></motion.div><div className="grid grid-cols-2 gap-4">{[{n:500,s:"+",l:"Students helped"},{n:1200,s:"+",l:"Resumes reviewed"},{n:92,s:"%",l:"Found clearer paths"},{n:48,s:"hrs",l:"Average time saved"}].map((x,i)=><CountStat key={x.l} {...x} delay={i*.08}/>)}</div></div></section>
    <section id="about" className="mx-auto max-w-5xl px-5 py-24 text-center sm:px-8"><motion.div {...rise}><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-gradient-warm text-accent-foreground shadow-warm"><Users/></span><h2 className="mt-6 text-4xl font-extrabold">Talent is everywhere. Opportunity should be too.</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-muted-foreground">CareerBridge is a college project exploring how responsible AI can make career support more accessible, personal, and actionable.</p></motion.div></section>
    <footer className="border-t border-border px-5 py-8"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-4 text-sm text-muted-foreground sm:flex-row"><strong className="font-display text-foreground">CareerBridge</strong><span>Built for students, with ambition.</span><div className="flex gap-5"><a href="#features">Features</a><a href="#about">About</a></div></div></footer>
  </motion.main>;
}

function CountStat({n,s,l,delay}:{n:number;s:string;l:string;delay:number}) { const [v,setV]=useState(0); return <motion.div {...rise} transition={{delay}} onViewportEnter={()=>{let x=0;const timer=setInterval(()=>{x+=Math.ceil(n/30);if(x>=n){x=n;clearInterval(timer)}setV(x)},35)}} className="rounded-2xl border border-border bg-card p-6 shadow-soft"><div className="font-display text-3xl font-extrabold text-primary">{v}{s}</div><div className="mt-1 text-sm text-muted-foreground">{l}</div></motion.div> }

function Dashboard({agent,setAgent}:{agent:Agent;setAgent:(a:Agent)=>void}) {
  const tabs=[{id:"overview" as const,title:"Overview",icon:LayoutDashboard},...agents.map(a=>({id:a.id,title:a.short,icon:a.icon}))];
  return <motion.main initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-10}} className="mx-auto grid max-w-[1500px] lg:grid-cols-[245px_minmax(0,1fr)]">
    <aside className="sticky top-18 hidden h-[calc(100vh-4.5rem)] border-r border-border bg-surface px-4 py-7 backdrop-blur-xl lg:block"><p className="px-3 text-xs font-bold uppercase text-muted-foreground">AI Career Team</p><div className="mt-4 grid gap-2">{tabs.map(t=><Button key={t.id} variant={agent===t.id?"secondary":"ghost"} className={`h-11 justify-start ${agent===t.id?"text-primary":"text-muted-foreground"}`} onClick={()=>setAgent(t.id)}><t.icon/>{t.title}</Button>)}</div><div className="absolute bottom-6 left-4 right-4 rounded-xl border border-primary/20 bg-secondary p-4"><p className="text-xs font-bold text-primary">CAREER READINESS</p><div className="mt-2 h-2 overflow-hidden rounded-full bg-background"><motion.div initial={{width:0}} animate={{width:"68%"}} className="h-full rounded-full bg-gradient-brand"/></div><p className="mt-2 text-xs text-muted-foreground">You’re making great progress.</p></div></aside>
    <div className="min-w-0 px-4 py-6 sm:px-8 lg:px-10 lg:py-9">
      <div className="mb-5 flex gap-2 overflow-x-auto pb-2 lg:hidden">{tabs.map(t=><Button key={t.id} variant={agent===t.id?"default":"outline"} className="shrink-0" onClick={()=>setAgent(t.id)}><t.icon/>{t.title}</Button>)}</div>
      <AnimatePresence mode="wait"><motion.div key={agent} initial={{opacity:0,x:22}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-22}} transition={{duration:.28}}>{agent==="overview"?<Overview setAgent={setAgent}/>:agent==="resume"?<ResumeAgent/>:agent==="career"?<CareerAgent/>:agent==="scholarship"?<ScholarshipAgent/>:<JobsAgent/>}</motion.div></AnimatePresence>
    </div>
  </motion.main>;
}

function PageTitle({eyebrow,title,desc,icon:Icon}:{eyebrow:string;title:string;desc:string;icon:any}) { return <div className="mb-8 grid grid-cols-[minmax(0,1fr)_auto] items-start gap-4"><div className="min-w-0"><p className="text-xs font-bold uppercase text-primary">{eyebrow}</p><h1 className="mt-2 text-3xl font-extrabold sm:text-4xl">{title}</h1><p className="mt-2 text-muted-foreground">{desc}</p></div><div className="grid size-12 shrink-0 place-items-center rounded-2xl bg-secondary text-primary"><Icon/></div></div> }
function Panel({children,className=""}:{children:ReactNode;className?:string}) { return <div className={`rounded-2xl border border-border bg-card p-5 shadow-soft backdrop-blur-md sm:p-6 ${className}`}>{children}</div> }

function Overview({setAgent}:{setAgent:(a:Agent)=>void}) { return <><div className="relative overflow-hidden rounded-2xl bg-gradient-brand p-7 text-primary-foreground shadow-glow sm:p-9"><div className="relative z-10 max-w-2xl"><p className="text-sm font-bold opacity-80">MONDAY, 21 SEPTEMBER</p><h1 className="mt-3 text-3xl font-extrabold sm:text-4xl">Good evening, Aarav.</h1><p className="mt-3 opacity-85">One thoughtful step today can change where you are a year from now.</p></div><Sparkles className="absolute -bottom-4 right-6 size-32 opacity-10"/></div><h2 className="mt-9 text-xl font-bold">Your progress at a glance</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[{l:"Resume score",v:"72/100",i:FileSearch},{l:"Career match",v:"89%",i:Target},{l:"Scholarships",v:"12 found",i:Award},{l:"Job matches",v:"24 roles",i:BriefcaseBusiness}].map(x=><Panel key={x.l}><x.i className="text-primary"/><p className="mt-5 text-sm text-muted-foreground">{x.l}</p><p className="mt-1 font-display text-2xl font-extrabold">{x.v}</p></Panel>)}</div><h2 className="mt-9 text-xl font-bold">Continue exploring</h2><div className="mt-4 grid gap-4 sm:grid-cols-2">{agents.map(a=><motion.button whileHover={{y:-4}} key={a.id} onClick={()=>setAgent(a.id)} className="group flex items-center gap-4 rounded-2xl border border-border bg-card p-5 text-left shadow-soft"><span className={`grid size-11 shrink-0 place-items-center rounded-xl ${a.bg} ${a.color}`}><a.icon/></span><span className="min-w-0 flex-1"><strong className="block truncate">{a.title}</strong><span className="text-sm text-muted-foreground">{a.desc}</span></span><ArrowRight className="shrink-0 text-muted-foreground transition-transform group-hover:translate-x-1"/></motion.button>)}</div></> }

function ResumeAgent(){const [drag,setDrag]=useState(false),[file,setFile]=useState(""),[loading,setLoading]=useState(false),[done,setDone]=useState(false);const analyze=()=>{setLoading(true);setDone(false);setTimeout(()=>{setLoading(false);setDone(true)},1200)};return <><PageTitle eyebrow="Agent 01" title="Resume Evaluator" desc="Get practical feedback before your resume reaches a recruiter." icon={FileSearch}/><Panel><label onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);setFile(e.dataTransfer.files[0]?.name||"resume.pdf")}} className={`flex min-h-60 cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed p-7 text-center transition-all ${drag?"border-primary bg-secondary scale-[1.01]":"border-border bg-muted/35 hover:border-primary/60"}`}><input type="file" accept=".pdf" className="hidden" onChange={e=>setFile(e.target.files?.[0]?.name||"")}/><UploadCloud className="size-10 text-primary"/><h3 className="mt-4 text-lg font-bold">{file||"Drop your resume here"}</h3><p className="mt-2 text-sm text-muted-foreground">PDF only · maximum 10MB</p></label><Button variant="hero" size="lg" className="mt-5 w-full" onClick={analyze} disabled={loading}>{loading?<><span className="size-4 animate-spin rounded-full border-2 border-primary-foreground/30 border-t-primary-foreground"/>Analyzing...</>:<><Sparkles/>Analyze Resume</>}</Button></Panel><AnimatePresence>{done&&<motion.div initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} className="mt-6 grid gap-5 lg:grid-cols-[280px_1fr]"><Panel className="grid place-items-center text-center"><ScoreRing score={72}/><h3 className="mt-3 text-lg font-bold">Solid foundation</h3><p className="mt-1 text-sm text-muted-foreground">Your resume is on the right track.</p></Panel><Panel><h3 className="text-lg font-bold">Top improvements</h3><div className="mt-4 space-y-3">{["Add measurable impact to project bullets","Use stronger action verbs in experience","Move technical skills above education"].map((t,i)=><Suggestion key={t} text={t} n={i+1}/>)}</div><p className="mt-6 text-sm font-semibold">Missing sections</p><div className="mt-2 flex flex-wrap gap-2"><span className="rounded-full bg-destructive/10 px-3 py-1 text-xs font-bold text-destructive">Achievements</span><span className="rounded-full bg-warning/15 px-3 py-1 text-xs font-bold text-warning">Certifications</span></div></Panel></motion.div>}</AnimatePresence></>}
function ScoreRing({score}:{score:number}){return <div className="relative size-40"><svg className="size-full -rotate-90" viewBox="0 0 120 120"><circle cx="60" cy="60" r="51" fill="none" stroke="currentColor" strokeWidth="9" className="text-muted"/><motion.circle cx="60" cy="60" r="51" fill="none" stroke="currentColor" strokeWidth="9" strokeLinecap="round" className="text-primary" strokeDasharray="320" initial={{strokeDashoffset:320}} animate={{strokeDashoffset:320*(1-score/100)}} transition={{duration:1.2,ease:"easeOut"}}/></svg><div className="absolute inset-0 grid place-items-center"><div><strong className="font-display text-4xl">{score}</strong><span className="text-muted-foreground">/100</span><p className="text-xs font-bold text-primary">ATS SCORE</p></div></div></div>}
function Suggestion({text,n}:{text:string;n:number}){const [open,setOpen]=useState(false);return <button onClick={()=>setOpen(!open)} className="w-full rounded-xl border border-border bg-background/55 p-4 text-left"><span className="flex items-center gap-3"><span className="grid size-7 place-items-center rounded-lg bg-secondary text-xs font-bold text-primary">{n}</span><strong className="flex-1 text-sm">{text}</strong><ChevronDown className={`transition-transform ${open?"rotate-180":""}`}/></span><AnimatePresence>{open&&<motion.p initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}} className="overflow-hidden pl-10 pt-3 text-sm text-muted-foreground">Recruiters scan quickly. This change makes your value clearer and improves keyword relevance.</motion.p>}</AnimatePresence></button>}

function CareerAgent(){const [step,setStep]=useState(1),[stream,setStream]=useState(""),[interests,setInterests]=useState<string[]>([]),[done,setDone]=useState(false);const choices=["Science","Commerce","Arts"], chips=["Technology","Design","People","Research","Business","Public Service"];return <><PageTitle eyebrow="Agent 02" title="Career & Exam Counselor" desc="Build a direction around what you enjoy and where you perform best." icon={Compass}/><Panel><div className="mb-8 flex items-center">{[1,2,3].map((n,i)=><div key={n} className={`flex items-center ${i<2?"flex-1":""}`}><span className={`grid size-9 shrink-0 place-items-center rounded-full text-sm font-bold ${step>=n?"bg-primary text-primary-foreground":"bg-muted text-muted-foreground"}`}>{step>n?<Check/>:n}</span>{i<2&&<span className={`h-1 flex-1 ${step>n?"bg-primary":"bg-muted"}`}/>}</div>)}</div><AnimatePresence mode="wait"><motion.div key={step} initial={{opacity:0,x:20}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-20}}>{step===1&&<div><h3 className="text-xl font-bold">Choose your stream</h3><div className="mt-5 grid gap-3 sm:grid-cols-3">{choices.map(c=><button key={c} onClick={()=>setStream(c)} className={`rounded-2xl border p-6 text-left transition-all hover:-translate-y-1 ${stream===c?"border-primary bg-secondary shadow-glow":"border-border bg-background/50"}`}><BookOpen className="text-primary"/><strong className="mt-8 block">{c}</strong></button>)}</div></div>}{step===2&&<div><h3 className="text-xl font-bold">Enter your recent marks</h3><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Overall percentage" placeholder="e.g. 84"/><Field label="Strongest subject" placeholder="e.g. Mathematics"/></div></div>}{step===3&&<div><h3 className="text-xl font-bold">What interests you?</h3><div className="mt-5 flex flex-wrap gap-3">{chips.map(c=><button key={c} onClick={()=>setInterests(x=>x.includes(c)?x.filter(y=>y!==c):[...x,c])} className={`rounded-full border px-4 py-2.5 text-sm font-semibold transition-all ${interests.includes(c)?"border-primary bg-primary text-primary-foreground":"border-border bg-background"}`}>{c}</button>)}</div></div>}</motion.div></AnimatePresence><div className="mt-8 flex justify-between"><Button variant="outline" disabled={step===1} onClick={()=>setStep(step-1)}>Back</Button>{step<3?<Button variant="hero" onClick={()=>setStep(step+1)} disabled={step===1&&!stream}>Continue <ArrowRight/></Button>:<Button variant="warm" onClick={()=>setDone(true)}>Get Guidance <Sparkles/></Button>}</div></Panel>{done&&<motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="mt-6"><h2 className="mb-4 text-xl font-bold">Paths worth exploring</h2><div className="grid gap-4 md:grid-cols-3">{[{t:"Data Analyst",m:"94%",e:"CUET · IIT JAM"},{t:"Product Designer",m:"88%",e:"UCEED · NID DAT"},{t:"Economics Researcher",m:"81%",e:"CUET PG · RBI Grade B"}].map(x=><FlipCard key={x.t} {...x}/>)}</div></motion.div>}</>}
function Field({label,placeholder}:{label:string;placeholder:string}){return <label className="grid gap-2 text-sm font-semibold">{label}<input className="h-12 rounded-xl border border-input bg-background px-4 font-normal outline-none transition-shadow focus:ring-2 focus:ring-ring" placeholder={placeholder}/></label>}
function FlipCard({t,m,e}:{t:string;m:string;e:string}){const [open,setOpen]=useState(false);return <motion.button layout onClick={()=>setOpen(!open)} className="rounded-2xl border border-border bg-card p-5 text-left shadow-soft"><div className="flex items-start justify-between"><BriefcaseBusiness className="text-primary"/><span className="rounded-full bg-success/10 px-3 py-1 text-xs font-bold text-success">{m} fit</span></div><h3 className="mt-7 text-lg font-bold">{t}</h3><p className="mt-2 text-sm text-muted-foreground">{open?"Your analytical strengths and interest profile align strongly with this path.":"Tap to see why this path fits."}</p>{open&&<motion.div initial={{opacity:0}} animate={{opacity:1}} className="mt-4 border-t border-border pt-4 text-sm"><strong>Recommended exams</strong><p className="mt-1 text-primary">{e}</p></motion.div>}</motion.button>}

function ScholarshipAgent(){const [done,setDone]=useState(false);return <><PageTitle eyebrow="Agent 03" title="Scholarship & Resource Finder" desc="Find financial support and high-quality learning without the noise." icon={GraduationCap}/><Panel><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><SelectField label="Education" values={["Undergraduate","Postgraduate","Class 12"]}/><SelectField label="State" values={["Maharashtra","Karnataka","Delhi"]}/><SelectField label="Category" values={["General","OBC","SC","ST"]}/><Field label="Marks (%)" placeholder="e.g. 82"/></div><Button variant="hero" size="lg" className="mt-6" onClick={()=>setDone(true)}><Search/>Find Scholarships</Button></Panel>{done&&<motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}}><h2 className="mb-4 mt-8 text-xl font-bold">3 scholarships matched</h2><div className="grid gap-4 lg:grid-cols-3">{[{n:"HDFC Parivartan Scholarship",a:"₹75,000",d:"30 Sep"},{n:"Foundation for Excellence",a:"₹50,000",d:"12 Oct"},{n:"National Merit Scholarship",a:"₹20,000",d:"31 Oct"}].map((x,i)=><motion.div initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{delay:i*.1}} key={x.n}><Panel><div className="flex items-center justify-between"><Award className="text-accent"/><span className="text-xs font-bold text-destructive">Due {x.d}</span></div><h3 className="mt-6 font-bold">{x.n}</h3><p className="mt-2 font-display text-2xl font-extrabold text-primary">{x.a}</p><p className="mt-3 text-sm text-muted-foreground">For students with 75%+ marks and demonstrated financial need.</p><Button variant="outline" className="mt-5 w-full">View details <ArrowRight/></Button></Panel></motion.div>)}</div><Panel className="mt-6"><h2 className="text-xl font-bold">Free study resources</h2>{[{s:"Mathematics",r:["NPTEL Calculus","Khan Academy","3Blue1Brown"]},{s:"Computer Science",r:["CS50","NPTEL Python","freeCodeCamp"]}].map(x=><div key={x.s} className="mt-5"><p className="text-sm font-semibold">{x.s}</p><div className="mt-2 flex flex-wrap gap-2">{x.r.map(r=><span key={r} className="rounded-full bg-secondary px-3 py-2 text-xs font-bold text-primary">{r}</span>)}</div></div>)}</Panel></motion.div>}</>}
function SelectField({label,values}:{label:string;values:string[]}){return <label className="grid gap-2 text-sm font-semibold">{label}<select className="h-12 rounded-xl border border-input bg-background px-4 font-normal outline-none focus:ring-2 focus:ring-ring">{values.map(v=><option key={v}>{v}</option>)}</select></label>}

function JobsAgent(){const [done,setDone]=useState(false);const skills=["Python","SQL","React","Figma","Data Analysis","Communication"];return <><PageTitle eyebrow="Agent 04" title="Job Matcher" desc="See where your current skills can take you—and what to learn next." icon={BriefcaseBusiness}/><Panel><p className="text-sm font-bold">Skills found in your resume</p><div className="mt-4 flex flex-wrap gap-2">{skills.map((s,i)=><motion.span initial={{opacity:0,scale:.7}} animate={{opacity:1,scale:1}} transition={{delay:i*.07}} key={s} className="rounded-full border border-primary/20 bg-secondary px-4 py-2 text-sm font-semibold text-primary">{s}</motion.span>)}</div><Button variant="warm" size="lg" className="mt-6" onClick={()=>setDone(true)}><Search/>Find Matching Jobs</Button></Panel>{done&&<motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}}><h2 className="mb-4 mt-8 text-xl font-bold">Your strongest matches</h2><div className="space-y-4">{[{t:"Junior Data Analyst",c:"Nexora Labs",m:92,g:"Learn Power BI basics"},{t:"Product Operations Intern",c:"BrightPath",m:86,g:"Build stakeholder reporting skills"},{t:"Frontend Developer Intern",c:"Orbit Systems",m:78,g:"Strengthen TypeScript fundamentals"}].map((x,i)=><motion.div whileHover={{y:-4}} key={x.t}><Panel><div className="grid gap-5 sm:grid-cols-[minmax(0,1fr)_160px]"><div className="min-w-0"><span className="text-xs font-bold text-primary">{x.c}</span><h3 className="mt-1 text-xl font-bold">{x.t}</h3><p className="mt-3 text-sm text-muted-foreground"><strong className="text-foreground">Skill gap:</strong> {x.g}</p></div><div><div className="flex items-center justify-between text-sm"><span>Match</span><strong className="text-success">{x.m}%</strong></div><div className="mt-2 h-2.5 overflow-hidden rounded-full bg-muted"><motion.div initial={{width:0}} animate={{width:`${x.m}%`}} transition={{delay:i*.1,duration:.8}} className="h-full rounded-full bg-gradient-brand"/></div><Button variant="outline" className="mt-4 w-full">View role</Button></div></div></Panel></motion.div>)}</div></motion.div>}</>}